[build]
publish = "public"
command = "zola build"

[build.environment]
ZOLA_VERSION = "0.20.0"

[context.deploy-preview.environment]
ZOLA_VERSION = "0.20.0"

[context.branch-deploy.environment]
ZOLA_VERSION = "0.20.0"