title = "Josh Fairhead"
base_url = "https://cv.joshafairhead.com"
compile_sass = true
minify_html = true
generate_feeds = false
build_search_index = false

[extra]
# CV/job-hunting site
# Clean, professional, minimal design
